module(
    name = "circuitc",
)

bazel_dep(name = "rules_rust", version = "0.71.3")
bazel_dep(name = "rules_shell", version = "0.7.1")

bazel_dep(name = "buildifier_prebuilt", version = "8.5.1.3", dev_dependency = True)
bazel_dep(name = "ruff_prebuilt", version = "0.15.19.1", dev_dependency = True, repo_name = "ruff")
bazel_dep(name = "rules_python", version = "2.2.0", dev_dependency = True)
bazel_dep(name = "rules_shellcheck", version = "0.6.3", dev_dependency = True)

python = use_extension(
    "@rules_python//python/extensions:python.bzl",
    "python",
    dev_dependency = True,
)
python.defaults(python_version = "3.13")
python.override(minor_mapping = {"3.13": "3.13.13"})
python.toolchain(python_version = "3.13")
use_repo(python, "python_3_13")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    versions = ["1.93.0"],
)
use_repo(rust, "rust_toolchains")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.spec(
    features = ["derive"],
    package = "serde",
    version = "=1.0.228",
)
crate.spec(
    package = "serde_json",
    version = "=1.0.145",
)
crate.spec(
    package = "sha2",
    version = "=0.10.9",
)
crate.from_specs()
use_repo(crate, "crates")

register_toolchains("@rust_toolchains//:all")
