use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use crate::design::{
    Component, Design, SimulationAnalysis, SimulationAnalysisKind, SimulationModel,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SpiceNetNameMapping {
    pub net: String,
    pub node: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SpiceComponentNameMapping {
    pub path: String,
    pub reference: String,
    pub device: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SpiceNameMap {
    pub nets: Vec<SpiceNetNameMapping>,
    pub components: Vec<SpiceComponentNameMapping>,
}

pub(crate) struct LoweredSpice {
    pub(crate) netlist: String,
    pub(crate) name_map: SpiceNameMap,
}

pub(crate) fn lower_netlist(design: &Design) -> LoweredSpice {
    lower_netlist_with_analysis(design, None)
}

pub(crate) fn lower_analysis_netlist(
    design: &Design,
    analysis: &SimulationAnalysis,
) -> LoweredSpice {
    lower_netlist_with_analysis(design, Some(analysis))
}

fn lower_netlist_with_analysis(
    design: &Design,
    analysis: Option<&SimulationAnalysis>,
) -> LoweredSpice {
    let name_map = lower_names(design);
    let nodes: BTreeMap<&str, &str> = name_map
        .nets
        .iter()
        .map(|mapping| (mapping.net.as_str(), mapping.node.as_str()))
        .collect();
    let devices: BTreeMap<&str, &str> = name_map
        .components
        .iter()
        .map(|mapping| (mapping.path.as_str(), mapping.device.as_str()))
        .collect();

    let mut components: Vec<&Component> = design
        .components
        .iter()
        .filter(|component| component.simulation.is_some())
        .collect();
    components.sort_by(|left, right| left.path.cmp(&right.path));

    let mut output = String::new();
    writeln!(output, "* Generated by CircuitC from {}", design.name).unwrap();
    for mapping in &name_map.nets {
        writeln!(
            output,
            "* @circuitc-net {} {}",
            hex_encode(mapping.net.as_bytes()),
            mapping.node
        )
        .unwrap();
    }
    for mapping in &name_map.components {
        writeln!(
            output,
            "* @circuitc-device {} {} {}",
            hex_encode(mapping.path.as_bytes()),
            hex_encode(mapping.reference.as_bytes()),
            mapping.device
        )
        .unwrap();
    }

    for component in components {
        let model = component
            .simulation
            .as_ref()
            .expect("filtered simulation component must have a model");
        let (positive_pin, negative_pin, kind) = match model {
            SimulationModel::Resistor {
                positive_pin,
                negative_pin,
                ..
            } => (positive_pin.as_str(), negative_pin.as_str(), ""),
            SimulationModel::DcVoltageSource {
                positive_pin,
                negative_pin,
                ..
            } => (positive_pin.as_str(), negative_pin.as_str(), " DC"),
        };
        let value = component.value.quantity().spice_literal();
        let positive_net = component
            .net_for_pin(positive_pin)
            .expect("validated simulation pin must resolve");
        let negative_net = component
            .net_for_pin(negative_pin)
            .expect("validated simulation pin must resolve");
        let ac_excitation = match (analysis.map(|analysis| &analysis.kind), model) {
            (
                Some(SimulationAnalysisKind::AcLinearSweep {
                    source,
                    magnitude,
                    phase,
                    ..
                }),
                SimulationModel::DcVoltageSource { .. },
            ) if source == &component.path => format!(
                " AC {} {}",
                magnitude.spice_literal(),
                phase.spice_literal()
            ),
            _ => String::new(),
        };
        writeln!(
            output,
            "{} {} {}{} {}{}",
            devices[component.path.as_str()],
            nodes[positive_net],
            nodes[negative_net],
            kind,
            value,
            ac_excitation,
        )
        .unwrap();
    }
    if let Some(analysis) = analysis {
        match &analysis.kind {
            SimulationAnalysisKind::DcOperatingPoint => output.push_str(".OP\n"),
            SimulationAnalysisKind::AcLinearSweep {
                points,
                start_frequency,
                stop_frequency,
                ..
            } => writeln!(
                output,
                ".AC LIN {points} {} {}",
                start_frequency.spice_literal(),
                stop_frequency.spice_literal()
            )
            .unwrap(),
            SimulationAnalysisKind::Transient {
                step,
                stop,
                start,
                uic,
            } => {
                write!(
                    output,
                    ".TRAN {} {} {}",
                    step.spice_literal(),
                    stop.spice_literal(),
                    start.spice_literal()
                )
                .unwrap();
                if *uic {
                    output.push_str(" UIC");
                }
                output.push('\n');
            }
        }
    }
    output.push_str(".END\n");
    LoweredSpice {
        netlist: output,
        name_map,
    }
}

fn lower_names(design: &Design) -> SpiceNameMap {
    let mut emitted_net_names = BTreeSet::new();
    for component in design
        .components
        .iter()
        .filter(|component| component.simulation.is_some())
    {
        let model = component
            .simulation
            .as_ref()
            .expect("filtered simulation component must have a model");
        let (positive_pin, negative_pin) = match model {
            SimulationModel::Resistor {
                positive_pin,
                negative_pin,
                ..
            }
            | SimulationModel::DcVoltageSource {
                positive_pin,
                negative_pin,
                ..
            } => (positive_pin, negative_pin),
        };
        for pin in [positive_pin, negative_pin] {
            if let Some(net) = component.net_for_pin(pin) {
                emitted_net_names.insert(net);
            }
        }
    }
    let mut nets: Vec<_> = design
        .nets
        .iter()
        .filter(|net| net.is_ground || emitted_net_names.contains(net.name.as_str()))
        .collect();
    nets.sort_by(|left, right| left.name.cmp(&right.name));
    let net_case_counts = case_counts(
        nets.iter()
            .filter(|net| !net.is_ground)
            .map(|net| net.name.as_str()),
    );
    let mut used_nodes = BTreeSet::from(["0".to_owned()]);
    let mut net_mappings = Vec::new();

    for net in nets.iter().filter(|net| !net.is_ground) {
        let case_key = spice_case_key(&net.name);
        let can_preserve = spice_identifier_is_supported(&net.name)
            && !spice_node_is_reserved(&net.name)
            && net_case_counts[&case_key] == 1;
        if can_preserve {
            used_nodes.insert(case_key);
        }
    }
    for net in nets {
        let node = if net.is_ground {
            "0".to_owned()
        } else {
            let case_key = spice_case_key(&net.name);
            let can_preserve = spice_identifier_is_supported(&net.name)
                && !spice_node_is_reserved(&net.name)
                && net_case_counts[&case_key] == 1;
            if can_preserve {
                net.name.clone()
            } else {
                unique_mangled("CCN", &net.name, &mut used_nodes)
            }
        };
        net_mappings.push(SpiceNetNameMapping {
            net: net.name.clone(),
            node,
        });
    }

    let mut components: Vec<_> = design
        .components
        .iter()
        .filter(|component| component.simulation.is_some())
        .collect();
    components.sort_by(|left, right| left.path.cmp(&right.path));
    let reference_case_counts = case_counts(
        components
            .iter()
            .map(|component| component.reference.as_str()),
    );
    let mut used_devices = BTreeSet::new();
    for component in &components {
        let key = spice_case_key(&component.reference);
        if component_reference_is_preservable(component, &reference_case_counts) {
            used_devices.insert(key);
        }
    }
    let mut component_mappings = Vec::new();
    for component in components {
        let can_preserve = component_reference_is_preservable(component, &reference_case_counts);
        let device = if can_preserve {
            component.reference.clone()
        } else {
            let prefix = match component
                .simulation
                .as_ref()
                .expect("filtered simulation component must have a model")
            {
                SimulationModel::Resistor { .. } => "RCC",
                SimulationModel::DcVoltageSource { .. } => "VCC",
            };
            unique_mangled(
                prefix,
                &format!("{}\0{}", component.reference, component.path),
                &mut used_devices,
            )
        };
        component_mappings.push(SpiceComponentNameMapping {
            path: component.path.clone(),
            reference: component.reference.clone(),
            device,
        });
    }

    SpiceNameMap {
        nets: net_mappings,
        components: component_mappings,
    }
}

fn component_reference_is_preservable(
    component: &Component,
    reference_case_counts: &BTreeMap<String, usize>,
) -> bool {
    let compatible_prefix = match component
        .simulation
        .as_ref()
        .expect("filtered simulation component must have a model")
    {
        SimulationModel::Resistor { .. } => component
            .reference
            .bytes()
            .next()
            .is_some_and(|byte| matches!(byte, b'R' | b'r')),
        SimulationModel::DcVoltageSource { .. } => component
            .reference
            .bytes()
            .next()
            .is_some_and(|byte| matches!(byte, b'V' | b'v')),
    };
    compatible_prefix
        && spice_identifier_is_supported(&component.reference)
        && reference_case_counts[&spice_case_key(&component.reference)] == 1
}

fn case_counts<'a>(values: impl Iterator<Item = &'a str>) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    for value in values {
        *counts.entry(spice_case_key(value)).or_insert(0) += 1;
    }
    counts
}

fn spice_case_key(value: &str) -> String {
    value.to_ascii_uppercase()
}

fn spice_identifier_is_supported(value: &str) -> bool {
    !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
}

fn spice_node_is_reserved(value: &str) -> bool {
    value == "0" || value.eq_ignore_ascii_case("GND")
}

fn unique_mangled(prefix: &str, source: &str, used_case_keys: &mut BTreeSet<String>) -> String {
    let base = format!("{prefix}_{}", hex_encode(source.as_bytes()));
    let mut candidate = base.clone();
    let mut discriminator = 0_u64;
    while !used_case_keys.insert(spice_case_key(&candidate)) {
        discriminator += 1;
        candidate = format!("{base}_{discriminator}");
    }
    candidate
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(encoded, "{byte:02X}").unwrap();
    }
    encoded
}

#[cfg(test)]
mod tests {
    use std::fmt::Write as _;

    use crate::demo::voltage_divider;
    use crate::design::{
        Component, ComponentValue, Design, Net, SimulationAnalysis, SimulationAnalysisKind,
    };
    use crate::quantity::{Quantity, Unit};

    use super::{
        LoweredSpice, SpiceComponentNameMapping, SpiceNameMap, SpiceNetNameMapping,
        lower_analysis_netlist, lower_netlist,
    };

    #[test]
    fn legacy_lowering_has_exact_output_and_no_implicit_analysis() {
        let lowered = lower_netlist(&voltage_divider());
        assert_exact_lowering(
            lowered,
            &[
                (
                    "divider.analysis.input",
                    "646976696465722E616E616C797369732E696E707574",
                    "V1",
                    "5631",
                    "V1",
                    "V1 VIN 0 DC 10",
                ),
                (
                    "divider.r_bottom",
                    "646976696465722E725F626F74746F6D",
                    "R2",
                    "5232",
                    "R2",
                    "R2 VOUT 0 10e3",
                ),
                (
                    "divider.r_top",
                    "646976696465722E725F746F70",
                    "R1",
                    "5231",
                    "R1",
                    "R1 VIN VOUT 10e3",
                ),
            ],
            None,
        );
    }

    #[test]
    fn lowers_dc_analysis_to_exactly_one_operating_point_directive() {
        let design = voltage_divider();
        let analysis = SimulationAnalysis {
            path: "sim.dc".to_owned(),
            kind: SimulationAnalysisKind::DcOperatingPoint,
        };
        assert_exact_lowering(
            lower_analysis_netlist(&design, &analysis),
            &standard_rows("V1 VIN 0 DC 10"),
            Some(".OP"),
        );
    }

    #[test]
    fn lowers_ac_analysis_and_selected_source_excitation_exactly() {
        let mut design = voltage_divider();
        let mut bias = design
            .components
            .iter()
            .find(|component| component.path == "divider.analysis.input")
            .expect("fixture source must exist")
            .clone();
        bias.path = "divider.analysis.bias".to_owned();
        bias.reference = "V2".to_owned();
        design.components.push(bias);
        let analysis = SimulationAnalysis {
            path: "sim.ac".to_owned(),
            kind: SimulationAnalysisKind::AcLinearSweep {
                source: "divider.analysis.input".to_owned(),
                points: 11,
                start_frequency: Quantity::new(10, 0, Unit::Hertz),
                stop_frequency: Quantity::new(25, 2, Unit::Hertz),
                magnitude: Quantity::new(1, 0, Unit::Volt),
                phase: Quantity::new(-90, 0, Unit::Degree),
            },
        };
        assert_exact_lowering(
            lower_analysis_netlist(&design, &analysis),
            &[
                (
                    "divider.analysis.bias",
                    "646976696465722E616E616C797369732E62696173",
                    "V2",
                    "5632",
                    "V2",
                    "V2 VIN 0 DC 10",
                ),
                (
                    "divider.analysis.input",
                    "646976696465722E616E616C797369732E696E707574",
                    "V1",
                    "5631",
                    "V1",
                    "V1 VIN 0 DC 10 AC 1 -90",
                ),
                (
                    "divider.r_bottom",
                    "646976696465722E725F626F74746F6D",
                    "R2",
                    "5232",
                    "R2",
                    "R2 VOUT 0 10e3",
                ),
                (
                    "divider.r_top",
                    "646976696465722E725F746F70",
                    "R1",
                    "5231",
                    "R1",
                    "R1 VIN VOUT 10e3",
                ),
            ],
            Some(".AC LIN 11 10 2500"),
        );
    }

    #[test]
    fn lowers_transient_analysis_with_uic_if_and_only_if_requested() {
        let design = voltage_divider();
        let transient = |uic| SimulationAnalysis {
            path: "sim.tran".to_owned(),
            kind: SimulationAnalysisKind::Transient {
                step: Quantity::new(2, -6, Unit::Second),
                stop: Quantity::new(10, -3, Unit::Second),
                start: Quantity::new(0, 0, Unit::Second),
                uic,
            },
        };
        assert_exact_lowering(
            lower_analysis_netlist(&design, &transient(true)),
            &standard_rows("V1 VIN 0 DC 10"),
            Some(".TRAN 2e-6 10e-3 0 UIC"),
        );
        assert_exact_lowering(
            lower_analysis_netlist(&design, &transient(false)),
            &standard_rows("V1 VIN 0 DC 10"),
            Some(".TRAN 2e-6 10e-3 0"),
        );
    }

    #[test]
    fn simulator_lowering_reads_the_component_value() {
        let mut design = voltage_divider();
        design.components[0].value = ComponentValue::Resistance(Quantity::new(22, 3, Unit::Ohm));
        design
            .validate()
            .expect("updated exact component value must remain valid");

        let lowered = lower_netlist(&design);
        assert!(lowered.netlist.contains("R1 VIN VOUT 22e3"));
    }

    #[test]
    fn reserved_non_ground_alias_does_not_collapse_into_ground() {
        let mut design = voltage_divider();
        rename_net(&mut design, "GND", "REF0");
        rename_net(&mut design, "VIN", "GND");
        design.validate().expect("renamed design must be valid");
        let lowered = lower_netlist(&design);
        let ground = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "REF0")
            .expect("ground mapping must exist");
        let ordinary_gnd = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "GND")
            .expect("ordinary GND mapping must exist");
        assert_eq!(ground.node, "0");
        assert_ne!(ordinary_gnd.node, "0");
        assert!(ordinary_gnd.node.starts_with("CCN_"));
        assert!(
            lowered
                .netlist
                .contains(&format!("V1 {} 0 DC 10", ordinary_gnd.node))
        );
    }

    #[test]
    fn unsupported_and_case_colliding_net_names_are_lowered_injectively() {
        let mut design = voltage_divider();
        rename_net(&mut design, "VIN", "signal-a");
        rename_net(&mut design, "VOUT", "SIGNAL-A");
        design.validate().expect("canonical names remain valid");
        let lowered = lower_netlist(&design);
        let first = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "signal-a")
            .expect("first mapping must exist");
        let second = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "SIGNAL-A")
            .expect("second mapping must exist");
        assert_ne!(
            first.node.to_ascii_uppercase(),
            second.node.to_ascii_uppercase()
        );
        for node in [&first.node, &second.node] {
            assert!(
                node.bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
            );
        }
    }

    #[test]
    fn standalone_name_map_excludes_declared_nets_absent_from_device_lines() {
        let mut design = voltage_divider();
        design.nets.push(Net {
            name: "UNUSED".to_owned(),
            is_ground: false,
        });
        design
            .validate()
            .expect("an unused net remains valid intent");

        let lowered = lower_netlist(&design);
        assert!(
            lowered
                .name_map
                .nets
                .iter()
                .all(|mapping| mapping.net != "UNUSED")
        );
        assert!(!lowered.netlist.contains("554E55534544"));
    }

    #[test]
    fn arbitrary_and_wrong_prefix_references_use_model_owned_names() {
        let mut design = voltage_divider();
        component_mut(&mut design, "divider.analysis.input").reference =
            "arbitrary-name".to_owned();
        component_mut(&mut design, "divider.r_bottom").reference = "XSAFE".to_owned();
        component_mut(&mut design, "divider.r_top").reference = "1bad".to_owned();

        assert_exact_lowering(
            lower_netlist(&design),
            &[
                (
                    "divider.analysis.input",
                    "646976696465722E616E616C797369732E696E707574",
                    "arbitrary-name",
                    "6172626974726172792D6E616D65",
                    "VCC_6172626974726172792D6E616D6500646976696465722E616E616C797369732E696E707574",
                    "VCC_6172626974726172792D6E616D6500646976696465722E616E616C797369732E696E707574 VIN 0 DC 10",
                ),
                (
                    "divider.r_bottom",
                    "646976696465722E725F626F74746F6D",
                    "XSAFE",
                    "5853414645",
                    "RCC_585341464500646976696465722E725F626F74746F6D",
                    "RCC_585341464500646976696465722E725F626F74746F6D VOUT 0 10e3",
                ),
                (
                    "divider.r_top",
                    "646976696465722E725F746F70",
                    "1bad",
                    "31626164",
                    "RCC_3162616400646976696465722E725F746F70",
                    "RCC_3162616400646976696465722E725F746F70 VIN VOUT 10e3",
                ),
            ],
            None,
        );
    }

    #[test]
    fn cross_kind_references_cannot_change_the_spice_device_model() {
        let mut design = voltage_divider();
        component_mut(&mut design, "divider.r_top").reference = "V1".to_owned();

        assert_exact_lowering(
            lower_netlist(&design),
            &[
                (
                    "divider.analysis.input",
                    "646976696465722E616E616C797369732E696E707574",
                    "V1",
                    "5631",
                    "VCC_563100646976696465722E616E616C797369732E696E707574",
                    "VCC_563100646976696465722E616E616C797369732E696E707574 VIN 0 DC 10",
                ),
                (
                    "divider.r_bottom",
                    "646976696465722E725F626F74746F6D",
                    "R2",
                    "5232",
                    "R2",
                    "R2 VOUT 0 10e3",
                ),
                (
                    "divider.r_top",
                    "646976696465722E725F746F70",
                    "V1",
                    "5631",
                    "RCC_563100646976696465722E725F746F70",
                    "RCC_563100646976696465722E725F746F70 VIN VOUT 10e3",
                ),
            ],
            None,
        );
    }

    #[test]
    fn lowercase_model_compatible_references_are_preserved_exactly() {
        let mut design = voltage_divider();
        component_mut(&mut design, "divider.analysis.input").reference = "v1".to_owned();
        component_mut(&mut design, "divider.r_bottom").reference = "r2".to_owned();
        component_mut(&mut design, "divider.r_top").reference = "r1".to_owned();

        assert_exact_lowering(
            lower_netlist(&design),
            &[
                (
                    "divider.analysis.input",
                    "646976696465722E616E616C797369732E696E707574",
                    "v1",
                    "7631",
                    "v1",
                    "v1 VIN 0 DC 10",
                ),
                (
                    "divider.r_bottom",
                    "646976696465722E725F626F74746F6D",
                    "r2",
                    "7232",
                    "r2",
                    "r2 VOUT 0 10e3",
                ),
                (
                    "divider.r_top",
                    "646976696465722E725F746F70",
                    "r1",
                    "7231",
                    "r1",
                    "r1 VIN VOUT 10e3",
                ),
            ],
            None,
        );
    }

    #[test]
    fn case_colliding_component_references_are_lowered_exactly_and_injectively() {
        let mut design = voltage_divider();
        component_mut(&mut design, "divider.r_bottom").reference = "Rfoo".to_owned();
        component_mut(&mut design, "divider.r_top").reference = "RFOO".to_owned();

        assert_exact_lowering(
            lower_netlist(&design),
            &[
                (
                    "divider.analysis.input",
                    "646976696465722E616E616C797369732E696E707574",
                    "V1",
                    "5631",
                    "V1",
                    "V1 VIN 0 DC 10",
                ),
                (
                    "divider.r_bottom",
                    "646976696465722E725F626F74746F6D",
                    "Rfoo",
                    "52666F6F",
                    "RCC_52666F6F00646976696465722E725F626F74746F6D",
                    "RCC_52666F6F00646976696465722E725F626F74746F6D VOUT 0 10e3",
                ),
                (
                    "divider.r_top",
                    "646976696465722E725F746F70",
                    "RFOO",
                    "52464F4F",
                    "RCC_52464F4F00646976696465722E725F746F70",
                    "RCC_52464F4F00646976696465722E725F746F70 VIN VOUT 10e3",
                ),
            ],
            None,
        );
    }

    #[test]
    fn preserved_component_name_is_reserved_before_mangling() {
        let mut design = voltage_divider();
        let top = component_mut(&mut design, "divider.r_top");
        top.path = "a".to_owned();
        top.reference = "X".to_owned();
        component_mut(&mut design, "divider.r_bottom").reference = "RCC_580061".to_owned();

        assert_exact_lowering(
            lower_netlist(&design),
            &[
                (
                    "a",
                    "61",
                    "X",
                    "58",
                    "RCC_580061_1",
                    "RCC_580061_1 VIN VOUT 10e3",
                ),
                (
                    "divider.analysis.input",
                    "646976696465722E616E616C797369732E696E707574",
                    "V1",
                    "5631",
                    "V1",
                    "V1 VIN 0 DC 10",
                ),
                (
                    "divider.r_bottom",
                    "646976696465722E725F626F74746F6D",
                    "RCC_580061",
                    "5243435F353830303631",
                    "RCC_580061",
                    "RCC_580061 VOUT 0 10e3",
                ),
            ],
            None,
        );
    }

    #[test]
    fn mangled_names_cannot_collide_with_preserved_source_names() {
        let mut design = voltage_divider();
        rename_net(&mut design, "VIN", "0");
        rename_net(&mut design, "VOUT", "CCN_30");
        design.validate().expect("canonical names remain valid");
        let lowered = lower_netlist(&design);
        let first = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "0")
            .expect("reserved source mapping must exist");
        let second = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "CCN_30")
            .expect("preserved source mapping must exist");
        assert_ne!(
            first.node.to_ascii_uppercase(),
            second.node.to_ascii_uppercase()
        );
    }

    fn rename_net(design: &mut crate::design::Design, old: &str, new: &str) {
        design
            .nets
            .iter_mut()
            .find(|net| net.name == old)
            .expect("source net must exist")
            .name = new.to_owned();
        for connection in design
            .components
            .iter_mut()
            .flat_map(|component| &mut component.connections)
        {
            if let crate::design::ConnectionState::Connected(net) = &mut connection.state
                && net == old
            {
                *net = new.to_owned();
            }
        }
        for port in design
            .modules
            .iter_mut()
            .flat_map(|module| &mut module.ports)
        {
            if let crate::design::ConnectionState::Connected(net) = &mut port.state
                && net == old
            {
                *net = new.to_owned();
            }
        }
        for route in &mut design.board.routes {
            if route.net == old {
                route.net = new.to_owned();
            }
        }
    }

    type ExpectedRow<'a> = (&'a str, &'a str, &'a str, &'a str, &'a str, &'a str);

    fn standard_rows(voltage_line: &str) -> [ExpectedRow<'_>; 3] {
        [
            (
                "divider.analysis.input",
                "646976696465722E616E616C797369732E696E707574",
                "V1",
                "5631",
                "V1",
                voltage_line,
            ),
            (
                "divider.r_bottom",
                "646976696465722E725F626F74746F6D",
                "R2",
                "5232",
                "R2",
                "R2 VOUT 0 10e3",
            ),
            (
                "divider.r_top",
                "646976696465722E725F746F70",
                "R1",
                "5231",
                "R1",
                "R1 VIN VOUT 10e3",
            ),
        ]
    }

    fn assert_exact_lowering(
        lowered: LoweredSpice,
        expected_rows: &[ExpectedRow<'_>],
        directive: Option<&str>,
    ) {
        let expected_name_map = SpiceNameMap {
            nets: vec![
                SpiceNetNameMapping {
                    net: "GND".to_owned(),
                    node: "0".to_owned(),
                },
                SpiceNetNameMapping {
                    net: "VIN".to_owned(),
                    node: "VIN".to_owned(),
                },
                SpiceNetNameMapping {
                    net: "VOUT".to_owned(),
                    node: "VOUT".to_owned(),
                },
            ],
            components: expected_rows
                .iter()
                .map(
                    |(path, _, reference, _, device, _)| SpiceComponentNameMapping {
                        path: (*path).to_owned(),
                        reference: (*reference).to_owned(),
                        device: (*device).to_owned(),
                    },
                )
                .collect(),
        };
        assert_eq!(lowered.name_map, expected_name_map);

        let mut expected_netlist = String::from(
            "* Generated by CircuitC from voltage_divider\n\
             * @circuitc-net 474E44 0\n\
             * @circuitc-net 56494E VIN\n\
             * @circuitc-net 564F5554 VOUT\n",
        );
        for (_, path_hex, _, reference_hex, device, _) in expected_rows {
            writeln!(
                expected_netlist,
                "* @circuitc-device {path_hex} {reference_hex} {device}"
            )
            .unwrap();
        }
        for (_, _, _, _, _, component_line) in expected_rows {
            writeln!(expected_netlist, "{component_line}").unwrap();
        }
        if let Some(directive) = directive {
            writeln!(expected_netlist, "{directive}").unwrap();
        }
        expected_netlist.push_str(".END\n");
        assert_eq!(lowered.netlist, expected_netlist);
    }

    fn component_mut<'a>(design: &'a mut Design, path: &str) -> &'a mut Component {
        design
            .components
            .iter_mut()
            .find(|component| component.path == path)
            .expect("fixture component must exist")
    }
}
