use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use crate::design::{Component, Design, SimulationModel};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SpiceNetNameMapping {
    pub net: String,
    pub node: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SpiceComponentNameMapping {
    pub path: String,
    pub reference: String,
    pub device: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SpiceNameMap {
    pub nets: Vec<SpiceNetNameMapping>,
    pub components: Vec<SpiceComponentNameMapping>,
}

pub(crate) struct LoweredSpice {
    pub netlist: String,
    pub name_map: SpiceNameMap,
}

pub(crate) fn lower_netlist(design: &Design) -> LoweredSpice {
    let name_map = lower_names(design);
    let nodes: BTreeMap<&str, &str> = name_map
        .nets
        .iter()
        .map(|mapping| (mapping.net.as_str(), mapping.node.as_str()))
        .collect();
    let devices: BTreeMap<&str, &str> = name_map
        .components
        .iter()
        .map(|mapping| (mapping.path.as_str(), mapping.device.as_str()))
        .collect();

    let mut components: Vec<&Component> = design
        .components
        .iter()
        .filter(|component| component.simulation.is_some())
        .collect();
    components.sort_by(|left, right| left.path.cmp(&right.path));

    let mut output = String::new();
    writeln!(output, "* Generated by CircuitC from {}", design.name).unwrap();
    for mapping in &name_map.nets {
        writeln!(
            output,
            "* @circuitc-net {} {}",
            hex_encode(mapping.net.as_bytes()),
            mapping.node
        )
        .unwrap();
    }
    for mapping in &name_map.components {
        writeln!(
            output,
            "* @circuitc-device {} {} {}",
            hex_encode(mapping.path.as_bytes()),
            hex_encode(mapping.reference.as_bytes()),
            mapping.device
        )
        .unwrap();
    }

    for component in components {
        let model = component
            .simulation
            .as_ref()
            .expect("filtered simulation component must have a model");
        let (positive_pin, negative_pin, kind) = match model {
            SimulationModel::Resistor {
                positive_pin,
                negative_pin,
                ..
            } => (positive_pin.as_str(), negative_pin.as_str(), ""),
            SimulationModel::DcVoltageSource {
                positive_pin,
                negative_pin,
                ..
            } => (positive_pin.as_str(), negative_pin.as_str(), " DC"),
        };
        let value = component.value.quantity().spice_literal();
        let positive_net = component
            .net_for_pin(positive_pin)
            .expect("validated simulation pin must resolve");
        let negative_net = component
            .net_for_pin(negative_pin)
            .expect("validated simulation pin must resolve");
        writeln!(
            output,
            "{} {} {}{} {}",
            devices[component.path.as_str()],
            nodes[positive_net],
            nodes[negative_net],
            kind,
            value
        )
        .unwrap();
    }
    output.push_str(".END\n");
    LoweredSpice {
        netlist: output,
        name_map,
    }
}

fn lower_names(design: &Design) -> SpiceNameMap {
    let mut nets: Vec<_> = design.nets.iter().collect();
    nets.sort_by(|left, right| left.name.cmp(&right.name));
    let net_case_counts = case_counts(
        nets.iter()
            .filter(|net| !net.is_ground)
            .map(|net| net.name.as_str()),
    );
    let mut used_nodes = BTreeSet::from(["0".to_owned()]);
    let mut net_mappings = Vec::new();

    for net in nets.iter().filter(|net| !net.is_ground) {
        let case_key = spice_case_key(&net.name);
        let can_preserve = spice_identifier_is_supported(&net.name)
            && !spice_node_is_reserved(&net.name)
            && net_case_counts[&case_key] == 1;
        if can_preserve {
            used_nodes.insert(case_key);
        }
    }
    for net in nets {
        let node = if net.is_ground {
            "0".to_owned()
        } else {
            let case_key = spice_case_key(&net.name);
            let can_preserve = spice_identifier_is_supported(&net.name)
                && !spice_node_is_reserved(&net.name)
                && net_case_counts[&case_key] == 1;
            if can_preserve {
                net.name.clone()
            } else {
                unique_mangled("CCN", &net.name, &mut used_nodes)
            }
        };
        net_mappings.push(SpiceNetNameMapping {
            net: net.name.clone(),
            node,
        });
    }

    let mut components: Vec<_> = design
        .components
        .iter()
        .filter(|component| component.simulation.is_some())
        .collect();
    components.sort_by(|left, right| left.path.cmp(&right.path));
    let reference_case_counts = case_counts(
        components
            .iter()
            .map(|component| component.reference.as_str()),
    );
    let mut used_devices = BTreeSet::new();
    for component in &components {
        let key = spice_case_key(&component.reference);
        if spice_identifier_is_supported(&component.reference) && reference_case_counts[&key] == 1 {
            used_devices.insert(key);
        }
    }
    let mut component_mappings = Vec::new();
    for component in components {
        let case_key = spice_case_key(&component.reference);
        let can_preserve = spice_identifier_is_supported(&component.reference)
            && reference_case_counts[&case_key] == 1;
        let device = if can_preserve {
            component.reference.clone()
        } else {
            let prefix = match component
                .simulation
                .as_ref()
                .expect("filtered simulation component must have a model")
            {
                SimulationModel::Resistor { .. } => "RCC",
                SimulationModel::DcVoltageSource { .. } => "VCC",
            };
            unique_mangled(
                prefix,
                &format!("{}\0{}", component.reference, component.path),
                &mut used_devices,
            )
        };
        component_mappings.push(SpiceComponentNameMapping {
            path: component.path.clone(),
            reference: component.reference.clone(),
            device,
        });
    }

    SpiceNameMap {
        nets: net_mappings,
        components: component_mappings,
    }
}

fn case_counts<'a>(values: impl Iterator<Item = &'a str>) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    for value in values {
        *counts.entry(spice_case_key(value)).or_insert(0) += 1;
    }
    counts
}

fn spice_case_key(value: &str) -> String {
    value.to_ascii_uppercase()
}

fn spice_identifier_is_supported(value: &str) -> bool {
    !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
}

fn spice_node_is_reserved(value: &str) -> bool {
    value == "0" || value.eq_ignore_ascii_case("GND")
}

fn unique_mangled(prefix: &str, source: &str, used_case_keys: &mut BTreeSet<String>) -> String {
    let base = format!("{prefix}_{}", hex_encode(source.as_bytes()));
    let mut candidate = base.clone();
    let mut discriminator = 0_u64;
    while !used_case_keys.insert(spice_case_key(&candidate)) {
        discriminator += 1;
        candidate = format!("{base}_{discriminator}");
    }
    candidate
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(encoded, "{byte:02X}").unwrap();
    }
    encoded
}

#[cfg(test)]
mod tests {
    use crate::demo::voltage_divider;
    use crate::design::ComponentValue;
    use crate::quantity::{Quantity, Unit};

    use super::lower_netlist;

    #[test]
    fn preserves_safe_reference_fixture_names() {
        let lowered = lower_netlist(&voltage_divider());
        assert!(lowered.netlist.contains("R1 VIN VOUT 10e3"));
        assert!(lowered.netlist.contains("V1 VIN 0 DC 10"));
        assert!(lowered.netlist.ends_with(".END\n"));
        assert!(
            !lowered.netlist.contains(".OP\n"),
            "an analysis directive must never be synthesized without canonical intent"
        );
    }

    #[test]
    fn simulator_lowering_reads_the_component_value() {
        let mut design = voltage_divider();
        design.components[0].value = ComponentValue::Resistance(Quantity::new(22, 3, Unit::Ohm));
        design
            .validate()
            .expect("updated exact component value must remain valid");

        let lowered = lower_netlist(&design);
        assert!(lowered.netlist.contains("R1 VIN VOUT 22e3"));
    }

    #[test]
    fn reserved_non_ground_alias_does_not_collapse_into_ground() {
        let mut design = voltage_divider();
        rename_net(&mut design, "GND", "REF0");
        rename_net(&mut design, "VIN", "GND");
        design.validate().expect("renamed design must be valid");
        let lowered = lower_netlist(&design);
        let ground = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "REF0")
            .expect("ground mapping must exist");
        let ordinary_gnd = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "GND")
            .expect("ordinary GND mapping must exist");
        assert_eq!(ground.node, "0");
        assert_ne!(ordinary_gnd.node, "0");
        assert!(ordinary_gnd.node.starts_with("CCN_"));
        assert!(
            lowered
                .netlist
                .contains(&format!("V1 {} 0 DC 10", ordinary_gnd.node))
        );
    }

    #[test]
    fn unsupported_and_case_colliding_net_names_are_lowered_injectively() {
        let mut design = voltage_divider();
        rename_net(&mut design, "VIN", "signal-a");
        rename_net(&mut design, "VOUT", "SIGNAL-A");
        design.validate().expect("canonical names remain valid");
        let lowered = lower_netlist(&design);
        let first = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "signal-a")
            .expect("first mapping must exist");
        let second = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "SIGNAL-A")
            .expect("second mapping must exist");
        assert_ne!(
            first.node.to_ascii_uppercase(),
            second.node.to_ascii_uppercase()
        );
        for node in [&first.node, &second.node] {
            assert!(
                node.bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
            );
        }
    }

    #[test]
    fn case_colliding_component_references_are_lowered_injectively() {
        let mut design = voltage_divider();
        design.components[0].reference = "Rfoo".to_owned();
        design.components[1].reference = "RFOO".to_owned();
        design
            .validate()
            .expect("case-distinct canonical references remain valid");
        let lowered = lower_netlist(&design);
        let first = lowered
            .name_map
            .components
            .iter()
            .find(|mapping| mapping.reference == "Rfoo")
            .expect("first device mapping must exist");
        let second = lowered
            .name_map
            .components
            .iter()
            .find(|mapping| mapping.reference == "RFOO")
            .expect("second device mapping must exist");
        assert_ne!(
            first.device.to_ascii_uppercase(),
            second.device.to_ascii_uppercase()
        );
        assert!(first.device.starts_with('R'));
        assert!(second.device.starts_with('R'));
    }

    #[test]
    fn mangled_names_cannot_collide_with_preserved_source_names() {
        let mut design = voltage_divider();
        rename_net(&mut design, "VIN", "0");
        rename_net(&mut design, "VOUT", "CCN_30");
        design.validate().expect("canonical names remain valid");
        let lowered = lower_netlist(&design);
        let first = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "0")
            .expect("reserved source mapping must exist");
        let second = lowered
            .name_map
            .nets
            .iter()
            .find(|mapping| mapping.net == "CCN_30")
            .expect("preserved source mapping must exist");
        assert_ne!(
            first.node.to_ascii_uppercase(),
            second.node.to_ascii_uppercase()
        );
    }

    fn rename_net(design: &mut crate::design::Design, old: &str, new: &str) {
        design
            .nets
            .iter_mut()
            .find(|net| net.name == old)
            .expect("source net must exist")
            .name = new.to_owned();
        for connection in design
            .components
            .iter_mut()
            .flat_map(|component| &mut component.connections)
        {
            if let crate::design::ConnectionState::Connected(net) = &mut connection.state
                && net == old
            {
                *net = new.to_owned();
            }
        }
        for port in design
            .modules
            .iter_mut()
            .flat_map(|module| &mut module.ports)
        {
            if let crate::design::ConnectionState::Connected(net) = &mut port.state
                && net == old
            {
                *net = new.to_owned();
            }
        }
        for route in &mut design.board.routes {
            if route.net == old {
                route.net = new.to_owned();
            }
        }
    }
}
